blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/serilog-contrib/serilog-sinks-grafana-loki/discussions
    about: The place for questions, support and feature requests